### ISSUE TITLE
Extend YAML Application schema to add more abstractions

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#10]
The schema is still very close to the implementation. We can easily add some more abstractions to make the syntax more clear. 

A main improvement is for signals, which have topics coded by specially named parameters. This could be improved as follows:

```yaml
components:
  foo_old:
    component: foo::Foo
    parameters:
      x: 1
      a_topic: /foo
      b_topic: /bar

  foo_new:
    component: foo::Foo
    parameters:
      x: 1
    inputs:
      a: /foo
    outputs:
      b: /bar
```

An additional field may be to give the component a nicer display name `name: "Signal Processing"`, rather than the unique snake case name (`signal_processing`).

More abstractions in the schema will bring the YAML syntax closer to the frontend representation of applications, rather than the backend interpretation.

After making this change in the application schema, the YAML application interface in the state engine should be updated accordingly.
