### ISSUE TITLE
Define a syntax for sequenced events in the application schema

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#127]
This issue serves to improve support for sequential behavior with a new sequencing syntax. Sequential behavior means events that are explicitly triggered one after the other, rather than driven purely by component predicates.

In brief, a sequence is a list of steps that are triggered one after the other. Each sequence step can be a standard state event (load, unload, set parameter, etc). Sequence steps also include the option to wait; wait for a single predicate, wait for a condition, or wait for some timed duration.

After sequences are defined in the YAML, they can be started, restarted or aborted with a new `sequence` state events; component predicates, conditions and even sequences can also start, restart or abort a sequence. This approach is fully compatible with our event-driven and asynchronous behavior, but allows us to be more expressive with particular behaviors and sequential actions.

### Sequences explained

A simple sequence might look like this:

```yaml
sequences:
  my_sequence:
    - load:
        component: foo
    - wait:
        component: foo
        predicate: is_active
    - service:
        component: foo
        name: do_something
    - wait:
        seconds: 5
    - set:
        component: foo
        parameter: bar
        value: baz
```

The `wait` steps for component predicates or conditions can have an optional  timeout block, which define breakout events in case the predicate or condition are not true within the time limit

```yaml
wait:
  condition: foo
  timeout:
    seconds: 10.0
    events:
      unload:
        component: foo
```

There is also an `assert` which checks if a predicate or conditions is true right now, and otherwise triggers some breakout events

```yaml
assert:
  component: foo
  predicate: bar
  else:
    unload:
      component: foo
```

In both cases when breakout events are triggered, it aborts the current sequence. The syntax can maybe still be improved, but overall it allows for error recovery and branching logic (including sequences that start other sequences conditionally)

Finally, to manage sequences, the `sequence` event is used with either `start`, `restart`, or `abort` pointing to the name of the sequence:

```yaml
on_start:
  sequence:
    start: my_sequence
```
