### ISSUE TITLE
[Bug]: Unable to load joint trajectory controller for Kinova Gen3

### ISSUE THREAD

**Issue by sbtc-sipbb** [aica-technology/api#142]
### Image manifest

```Shell
#syntax=ghcr.io/aica-technology/app-builder:v1

[packages]
"@aica/base" = "v3.1.1"

# add components
"@aica/components/signal-processing" = "v1.0.1"
"@aica/components/auto-frame-calibration" = "v1.0.0"
"@aica/components/pose-detection" = "v1.0.2"
"@aica/components/task-optimization" = "v3.0.0"

# add hardware collections 
"@aica/collections/ur-collection" = "v3.0.4"
"@aica/collections/kinova-gen3-collection" = "v0.1.1"
```

### Brief description

I tried to replicate the example of Dominic from last Wednesday (commanding the robot through AICA -> Ros2Control joint trajectory controller -> position interface). But apparently the trajectory controller cannot be activated.   

### Steps to reproduce

Load the configuration file provided by Dominic and change the urdf to a custom version of the one from kinova-gen3-collection:
```yaml
# yaml-language-server: $schema=https://docs.aica.tech/schemas/1-2-0/application.schema.json

on_start:
  load:
    - { hardware: robot }
    - { hardware: robot, controller: broadcaster }
    - { hardware: robot, controller: trajectory }
  switch_controllers:
    - { hardware: robot, activate: [ broadcaster, trajectory ] }

hardware:
  robot:
    # Here I changed to a custom URDF based on the kinova-gen3-collection 
    # because this one is missing and the standard one from the kinova-gen3- 
    # collection has the wrong IP
    urdf: /home/ros2/examples/urdf/kinova_gen3.urdf 
    rate: 1000
    controllers:
      broadcaster:
        plugin: modulo_controllers/RobotStateBroadcaster
      trajectory:
        plugin: joint_trajectory_controller/JointTrajectoryController
        parameters:
          command_interfaces: [position]
          state_interfaces: [position]
```

As soon as I click on "Generate Graph", the joint_trajectory_controller disappears. The resulting file as copied from the AICA interface is then:
```yaml
on_start:
  load:
    - hardware: robot
    - hardware: robot
      controller: broadcaster
    - hardware: robot
      controller: trajectory
  switch_controllers:
    - hardware: robot
      activate:
        - broadcaster
        - trajectory
components: {}
hardware:
  robot:
    position:
      x: 500
      y: 0
    urdf: kinova_gen3_sbtc
    rate: 1000
    controllers:
      broadcaster:
        plugin: modulo_controllers/RobotStateBroadcaster
```

On top of that, I get the error (see log output)

### Relevant log output

```Shell
[INFO] [1711352926.223158380] [StateEventHandler]: Handling event SwitchControllersEvent called by on_start
[INFO] [1711352926.223163554] [StateEventHandler]: Switching controllers on hardware interface robot: activate [ broadcaster trajectory ], deactivate [ ]
[WARN] [1711352926.223171437] [robot.ControllerManager]: Could not 'activate' controller with name 'trajectory' because no controller with this name exists
[ERROR] [1711352926.223179238] [robot.ControllerManager]: Aborting, no controller is switched! ('STRICT' switch)
[DEBUG] [1711352926.223638798] [KortexMultiInterfaceHardware]: No controller active in LOW_LEVEL_SERVOING mode !
[DEBUG] [1711352926.224671070] [KortexMultiInterfaceHardware]: No controller active in LOW_LEVEL_SERVOING mode !
```

### Supporting information

Here is the urdf that I used (btw, would be nice to have support for file uploads in urdf format):
[kinova_gen3_sbtc.zip](https://github.com/aica-technology/api/files/14740465/kinova_gen3_sbtc.zip)
