### ISSUE TITLE
Remove self-targeting events for components (services, parameters, lifecycle)

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#167]
The first version of the application syntax allows component predicate-driven events to be self-targeting; the target component did not need to be specified in the event object. For example:

The following syntax would explicitly target component `foo` for these events:

```yaml
lifecycle:
  component: foo
  transition: activate
call_service:
  component: foo
  service: foo
set:
  component: foo
  parameter: foo
  value: bar
```

But if a predicate on component `foo` was calling these events, then the component target could be omitted.

```yaml
lifecycle: activate
call_service:
  service: foo
set:
  parameter: foo
  value: bar
```

The problem is that controllers also have services and dynamically settable parameters. In addition, these events can be triggered by other sources, such as conditions and sequences. This means that, while the syntax would permit a formulation like `lifecycle: activate` as valid, it would fail to function as expected when included under a controller, condition or sequence event.

The simple proposal therefore is to forbid this "self-targeting" syntactical shortcut. As we move more and more towards authoring our applications through the UI and not by hand, verbose but explicit syntax should be preferred to ambiguous shorthands. The plus side to being more restrictive with syntax is that it also simplifies the parser implementations.
