### ISSUE TITLE
[Request]: Sequence Fusion and Separation

### ISSUE THREAD

**Issue by MaelLF** [aica-technology/api#270]
### Description

Leave the possibility to separate / fusion sequences.
Fusion : select a set of consecutive blocks and group them into a compact "Sequence" block. This fused block acts as a container that preserves the execution order.
Separation : the invert effect of fusion.

### Who would benefit?

Improve modularity, readability and would make duplicating parts of code easier.

**Comment by eeberhard** [comment]
Hi @MaelLF, that's a very interesting idea! We will definitely consider designing and implementing this kind of behavior as suggested.

On a related note, we are currently in the design and planning phase for improving modularity and readability of complex applications, tentatively scoped to be ready around the summer.

In the short term, I can suggest a workaround using the YAML code editor. You can copy / paste, split and join sequence steps in text as necessary and then regenerate the graph. For example:

```yaml
sequences:
  sequence:
    steps:
      - set:
          parameter: frame
          value: top
          component: tf_to_signal
      - delay: 3
# <-- if you want to split a sequence here
      - set:
          parameter: frame
          value: left
          component: tf_to_signal
      - delay: 3
      - set:
          parameter: frame
          value: bottom
          component: tf_to_signal
      - delay: 3
```

```yaml
sequences:
  sequence:
    steps:
      - set:
          parameter: frame
          value: top
          component: tf_to_signal
      - delay: 3
# <-- you can insert a new sequence identifier and steps
  my_next_sequence:
    steps:
# -->
      - set:
          parameter: frame
          value: left
          component: tf_to_signal
      - delay: 3
      - set:
          parameter: frame
          value: bottom
          component: tf_to_signal
      - delay: 3
```

Of course this is less nice than the suggested UI implementation, and also comes with some caveats:

- You will probably lose existing custom edge paths if you re-order steps in code, and will definitely lose custom edge paths if you change the sequence identifier (i.e. splitting a new sequence as above as `my_next_sequence`) 
- When changing or adding a sequence identifier to existing steps, watch out for any references to that sequence identifier. For example, a condition looking for some `sequence: active` state will break if the sequence has been renamed to `my_next_sequence`. Same with the command to `start: sequence`. However, all edges going in and out from the actual steps should be independent of the sequence name.
