### ISSUE TITLE
Define 2-0-6 application schema with explicit parameter types

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#296]
The application schema should allow parameter values to be assigned specific value types, both when loading components and controllers as when setting parameters through events. 

This could be done by allowing a union of either the existing "scalar" parameter value or an object specifying the value and type, as suggested below.

```yaml
parameters:
  # current definition of a parameter value
  foo: abc
  # optional new definition of a parameter value
  bar:
    value: abc
    type: string
```
