### ISSUE TITLE
Add inputs, outputs controllers and position to hardware interfaces in application schema

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#31]
Similar to component descriptions, controller descriptions should allow the abstraction of input and output topic definition in separate fields `inputs` and `outputs`. The full hardware interface description should also include an optional position, same as components, so that the position of the node on the graph can be persisted.

Example:
```yaml
hardware_interfaces:
  robot:
    urdf: robot.urdf
    rate: 500
    position:
      x: 100
      y: 200
    controllers:
      my_controller:
        plugin: modulo_controllers/MyController
        parameters:
          foo: 1
        inputs:
          command: /my_command_topic
        outputs:
          state: /my_state_topic
```

Also, an optional `display_name` would be nice for the hardware interface.
