### ISSUE TITLE
Add hardware parameters to schema and docs

### ISSUE THREAD

**Issue by domire8** [aica-technology/api#67]
After https://github.com/aica-technology/dynamic-state-engine/pull/189, we need to update the docs as well as the schema.

@eeberhard

**Comment by eeberhard** [comment]
What is your preference for the official syntax? DSE currently supports both.

```yaml
hardware:
  my_robot:
    urdf: foo.urdf
    rate: 500
    parameters:
      ip: 127.0.0.1
      gain: 100
```

```yaml
hardware:
  my_robot:
    urdf: foo.urdf
    parameters:
      rate: 500
      ip: 127.0.0.1
      gain: 100
```
