### ISSUE TITLE
Application schema for buttons is not correctly nested for multiple buttons

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#84]
As noted [here](https://github.com/aica-technology/frontend/blob/1d44f07150e2c172ebdd8e26f2e952975ce69076/src/utils/instances/application-instance-manager.tsx#L32-L36) after Front-End PR [#501](https://github.com/aica-technology/frontend/pull/501), the button schema is not correctly nested.

It currently defines the individual button properties (`on_click`, `position`, `display_name`) under the top-level Buttons object: 

```yaml
buttons:
  on_click:
    load: ...
```

But, the intended pattern is to have named buttons as part of the Buttons object:

```yaml
buttons:
  test_button:
    on_click:
      load: ...
  another_button:
    on_click:
      unload: ...
```

This is also how the backend and frontend parsers currently treat the button syntax.
